const page = document.body.dataset.page || '';
const shell = `
<header class="site-header content-header" id="siteHeader"><a class="brand" href="index.html#top" aria-label="Breathe Woods home"><img src="Pics/Brand/desktop-breathe-woods-logo.png" alt="Breathe Woods" /></a><div class="header-actions"><button class="book-button header-book" type="button" data-book>Book your stay</button><a class="contact-icon" href="https://wa.me/919967786444" aria-label="WhatsApp Breathe Woods"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.4 3.6A11.5 11.5 0 0 0 2.9 18.1L2 22l4-1a11.5 11.5 0 0 0 14.4-17.4Z"/><path d="M8 7.4c.3-.6.6-.6.9-.6h.5c.2 0 .4.1.5.4l.9 2.1c.1.2.1.4 0 .6l-.5.7c-.1.2-.1.3 0 .5.5.8 1.3 1.6 2.2 2.1.2.1.3.1.5 0l.7-.8c.2-.2.4-.2.6-.1l2 .9c.3.1.4.3.4.5v.5c0 .4-.2.7-.6.9-.5.2-1.3.4-2.3 0-1-.4-2.3-1.2-3.8-2.7-1.5-1.5-2.2-2.8-2.6-3.8-.3-.9-.1-1.7.1-2.2Z"/></svg></a><a class="contact-icon" href="tel:+919967786444" aria-label="Call Breathe Woods"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5.2 3.8 8 3.1l2 4.7-1.7 1.6a14.5 14.5 0 0 0 6.3 6.3l1.6-1.7 4.7 2-.7 2.8c-.2.8-.9 1.3-1.7 1.3C10.3 20.1 3.9 13.7 3.9 5.5c0-.8.5-1.5 1.3-1.7Z"/></svg></a><button class="menu-toggle" type="button" id="openMenu" aria-label="Open menu"><i></i><i></i></button></div></header>
<dialog class="menu-dialog" id="menuDialog" aria-labelledby="menu-title"><button class="dialog-close" type="button" id="closeMenu" aria-label="Close menu">×</button><p class="eyebrow dark">Breathe Woods</p><h2 id="menu-title">Explore the stay</h2><nav aria-label="Menu"><a href="index.html">Home</a><a href="stays.html">Stays</a><a href="property.html">The Property</a><a href="dining.html">Dining</a><a href="explore.html">Explore</a><a href="coming-soon.html">Information</a><a href="coming-soon.html">Contact</a></nav><div class="menu-social"><a href="https://wa.me/919967786444">WhatsApp</a><a href="tel:+919967786444">Call</a><a href="https://www.instagram.com/breathewoodstala/">Instagram</a><a href="https://www.facebook.com/breathewoods">Facebook</a><a href="https://www.youtube.com/channel/UCwoZZPta5wRSksa2wBjN7dw">YouTube</a></div><button class="book-button dark-button" type="button" data-book>Book your stay</button></dialog>
<dialog class="booking-dialog" id="bookingDialog"><button class="dialog-close" type="button" id="closeDialog" aria-label="Close">×</button><p class="eyebrow dark">Book your stay</p><h2>Choose your dates.</h2><p id="bookingSummary">Select check-in, check-out, and guests to continue to the booking system.</p><button class="book-button dark-button" type="button" id="closeBooking">Back to the stay</button></dialog>
<footer class="site-footer" id="contact"><a class="site-footer__brand" href="index.html"><img src="Pics/Brand/desktop-breathe-woods-logo.png" alt="Breathe Woods" /></a><address>Kakadshet Road, Off Tala–Indapur Road<br />Muthavli Village, Indapur, Raigad, Maharashtra 402120</address><div class="site-footer__contact"><a href="https://wa.me/919967786444">WhatsApp</a><a href="tel:+919967786444">Call</a><a href="https://www.instagram.com/breathewoodstala/">Instagram</a><a href="https://www.facebook.com/breathewoods">Facebook</a><a href="https://www.youtube.com/channel/UCwoZZPta5wRSksa2wBjN7dw">YouTube</a></div></footer>`;
document.body.insertAdjacentHTML('afterbegin', shell);
const pageLinks = document.createElement('nav');
pageLinks.className = 'page-next-links';
pageLinks.setAttribute('aria-label', 'Continue exploring Breathe Woods');
pageLinks.innerHTML = '<a href="index.html">Home</a><a href="stays.html">Stays</a><a href="property.html">Property</a><a href="dining.html">Dining</a><a href="explore.html">Explore</a><a href="information.html">Information</a><a href="contact.html">Contact</a>';
document.querySelector('main')?.append(pageLinks);
// The header belongs at the top; the shared footer must remain after the page's main content.
const injectedFooter = document.querySelector('.site-footer');
if (injectedFooter) document.body.appendChild(injectedFooter);
const header = document.querySelector('#siteHeader');
const menuDialog = document.querySelector('#menuDialog');
const bookingDialog = document.querySelector('#bookingDialog');
menuDialog.setAttribute('aria-label', 'Site menu');
menuDialog.removeAttribute('aria-labelledby');
menuDialog.querySelector('h2')?.remove();
const oldMenuLinks = menuDialog.querySelector('.menu-social');
if (oldMenuLinks) oldMenuLinks.outerHTML = '<div class="menu-contact-links" aria-label="Contact Breathe Woods"><a href="https://wa.me/919967786444" aria-label="Message Breathe Woods on WhatsApp"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 11.6a8.3 8.3 0 0 1-12.25 7.3L4 20l1.15-4.05A8.3 8.3 0 1 1 20.5 11.6Z"/><path d="M9 8.2c.2-.4.4-.4.6-.4h.4c.2 0 .3.1.4.3l.6 1.5c.1.2.1.3 0 .5l-.3.4c-.1.2-.1.3 0 .5.3.6.9 1.2 1.6 1.6.2.1.3.1.5 0l.5-.6c.1-.2.3-.2.5-.1l1.5.7c.2.1.3.2.3.4 0 .5-.2 1-.6 1.3-.5.3-1.3.3-2.4-.2-1-.5-2.1-1.3-3.1-2.3-1-1-1.7-2.1-2.1-3.1-.3-.9-.1-1.7.2-2.2Z"/></svg></a><a href="tel:+919967786444" aria-label="Call Breathe Woods"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7.1 3.7 9.5 6c.32.32.38.82.15 1.2L8.5 9.2a14.2 14.2 0 0 0 6.3 6.3l2-1.15c.39-.23.88-.17 1.2.15l2.3 2.4c.34.35.37.9.06 1.28l-1.25 1.48c-.37.44-.96.64-1.52.5C10.1 18.2 5.8 13.9 3.84 6.41c-.15-.56.06-1.15.5-1.52l1.48-1.25c.38-.3.93-.28 1.28.06Z"/></svg></a></div>';
window.addEventListener('scroll', () => header.classList.toggle('scrolled', window.scrollY > 40), {passive:true});
document.querySelector('#openMenu').addEventListener('click', () => menuDialog.showModal());
document.querySelector('#closeMenu').addEventListener('click', () => menuDialog.close());
document.querySelectorAll('[data-book]').forEach((button) => button.addEventListener('click', () => { if (menuDialog.open) menuDialog.close(); bookingDialog.showModal(); }));
document.querySelector('#closeDialog').addEventListener('click', () => bookingDialog.close());
document.querySelector('#closeBooking').addEventListener('click', () => bookingDialog.close());
document.querySelectorAll('[data-booking-form]').forEach((form) => form.addEventListener('submit', (event) => { event.preventDefault(); const data = new FormData(form); document.querySelector('#bookingSummary').textContent = `Requested stay: ${data.get('checkIn') || 'choose check-in'} to ${data.get('checkOut') || 'choose check-out'} · ${data.get('guests')} guest${data.get('guests') === '1' ? '' : 's'}.`; bookingDialog.showModal(); }));
menuDialog.querySelectorAll('a').forEach((link) => { if (link.textContent.trim() === 'Information') link.href = 'information.html'; if (link.textContent.trim() === 'Contact') link.href = 'contact.html'; });
document.querySelectorAll('.brand img, .site-footer__brand img').forEach((logo) => { logo.src = 'Pics/Brand/logowordmarkwhite.png'; logo.alt = 'Breathe Woods'; });

document.querySelectorAll('.menu-dialog .eyebrow.dark').forEach((label) => { label.classList.add('menu-brand-mark'); label.innerHTML = '<img src="Pics/Brand/desktop-breathe-woods-logo.png" alt="Breathe Woods">'; });

if (new URLSearchParams(window.location.search).get('sent') === '1') { const form = document.querySelector('.enquiry-form'); const confirmation = document.querySelector('.enquiry-form__confirmation'); if (form && confirmation) { form.reset(); confirmation.hidden = false; confirmation.scrollIntoView({ block: 'center' }); window.history.replaceState({}, '', `${window.location.pathname}${window.location.hash}`); } }
